-- TheDiamond — full v1.0 schema (data model 1.4). Whole model created up front
-- so the schema stays stable across all build stages.

create table users (
    id            bigint generated by default as identity primary key,
    email         varchar(255) not null unique,
    password_hash varchar(255) not null,
    role          varchar(20)  not null,
    is_banned     boolean      not null default false,
    created_at    timestamptz  not null default now()
);

create table creator_profiles (
    id                  bigint generated by default as identity primary key,
    user_id             bigint       not null unique references users (id) on delete cascade,
    name                varchar(120) not null,
    username            varchar(60)  not null unique,
    avatar_url          varchar(500),
    bio                 varchar(500),
    city                varchar(80)  not null,
    birth_date          date         not null,
    instagram_url       varchar(300),
    tiktok_url          varchar(300),
    threads_url         varchar(300),
    youtube_url         varchar(300),
    telegram_url        varchar(300),
    instagram_followers integer,
    tiktok_followers    integer,
    threads_followers   integer,
    youtube_followers   integer,
    is_approved         boolean      not null default false,
    created_at          timestamptz  not null default now()
);

create table creator_categories (
    creator_profile_id bigint      not null references creator_profiles (id) on delete cascade,
    category           varchar(20) not null,
    primary key (creator_profile_id, category)
);

create table brand_profiles (
    id           bigint generated by default as identity primary key,
    user_id      bigint       not null unique references users (id) on delete cascade,
    company_name varchar(200) not null,
    bin          varchar(12)  not null,
    website      varchar(300),
    phone        varchar(40)  not null,
    contact_name varchar(120) not null,
    is_approved  boolean      not null default false,
    created_at   timestamptz  not null default now()
);

create table campaigns (
    id                 bigint generated by default as identity primary key,
    brand_id           bigint        not null references brand_profiles (id) on delete cascade,
    title              varchar(200)  not null,
    description        varchar(3000) not null,
    category           varchar(20)   not null,
    reward_per_creator integer       not null,
    creators_needed    integer       not null,
    deadline           date          not null,
    requirements       text          not null,
    status             varchar(20)   not null,
    reject_reason      varchar(500),
    created_at         timestamptz   not null default now()
);

create table campaign_platforms (
    campaign_id bigint      not null references campaigns (id) on delete cascade,
    platform    varchar(20) not null,
    primary key (campaign_id, platform)
);

create table applications (
    id             bigint generated by default as identity primary key,
    campaign_id    bigint      not null references campaigns (id) on delete cascade,
    creator_id     bigint      not null references creator_profiles (id) on delete cascade,
    status         varchar(20) not null,
    submission_url varchar(500),
    reject_reason  varchar(500),
    resubmit_used  boolean     not null default false,
    applied_at     timestamptz not null default now(),
    submitted_at   timestamptz,
    reviewed_at    timestamptz,
    unique (campaign_id, creator_id)
);

create index idx_campaigns_status on campaigns (status);
create index idx_campaigns_brand on campaigns (brand_id);
create index idx_applications_campaign on applications (campaign_id);
create index idx_applications_creator on applications (creator_id);
