create table creator_social_proofs (
    id                bigint generated by default as identity primary key,
    creator_id        bigint       not null references creator_profiles (id) on delete cascade,
    platform          varchar(20)  not null,
    post_url          varchar(500) not null,
    screenshot_url    varchar(500),
    verification_code varchar(40)  not null,
    status            varchar(20)  not null,
    reject_reason     varchar(500),
    created_at        timestamptz  not null default now(),
    reviewed_at       timestamptz
);

create index idx_creator_social_proofs_creator on creator_social_proofs (creator_id);
create index idx_creator_social_proofs_status on creator_social_proofs (status);
