-- Email verification on users (auto-approve after confirmation)
alter table users add column email_verified boolean not null default false;
alter table users add column verification_code varchar(10);
alter table users add column verification_code_expires timestamptz;
-- one-time 500₸ "advertise us" reward marker
alter table users add column reward_task_paid boolean not null default false;

-- Wallets (every user has one, balance in whole tenge)
create table wallets (
    id         bigint generated by default as identity primary key,
    user_id    bigint      not null unique references users (id) on delete cascade,
    balance    bigint      not null default 0,
    created_at timestamptz not null default now()
);

create table wallet_transactions (
    id          bigint generated by default as identity primary key,
    wallet_id   bigint       not null references wallets (id) on delete cascade,
    amount      bigint       not null,          -- positive = credit, negative = debit
    type        varchar(30)  not null,          -- REWARD | CAMPAIGN_PAYOUT | WITHDRAWAL | REFUND | ADJUSTMENT
    description varchar(300),
    created_at  timestamptz  not null default now()
);
create index idx_wallet_tx_wallet on wallet_transactions (wallet_id);

-- Withdrawal requests (minimum 2000₸, moderated/paid by admin)
create table withdrawals (
    id            bigint generated by default as identity primary key,
    user_id       bigint       not null references users (id) on delete cascade,
    amount        bigint       not null,
    status        varchar(20)  not null,        -- PENDING | PAID | REJECTED
    requisites    varchar(300) not null,        -- Kaspi / card number, etc.
    reject_reason varchar(500),
    created_at    timestamptz  not null default now(),
    reviewed_at   timestamptz
);
create index idx_withdrawals_user on withdrawals (user_id);
create index idx_withdrawals_status on withdrawals (status);

-- In-app notifications (generic send(userId, title, body))
create table notifications (
    id         bigint generated by default as identity primary key,
    user_id    bigint       not null references users (id) on delete cascade,
    title      varchar(200) not null,
    body       varchar(1000) not null,
    is_read    boolean      not null default false,
    created_at timestamptz  not null default now()
);
create index idx_notifications_user on notifications (user_id);
