-- Pivot: influencer-ads marketplace -> C2C marketplace for used phones.
--
-- Everything campaign/creator/brand/wallet-shaped is dropped. What survives is the
-- account layer (users + email verification + password reset) and notifications.
-- New domain: listings (объявления) -> deals (сделки) + favourites.
--
-- Deals carry no money: the buyer requests, the seller accepts, payment happens
-- offline. That's why the wallet tables go away instead of being repurposed.

drop table if exists applications;
drop table if exists campaign_platforms;
drop table if exists campaigns;
drop table if exists creator_social_proofs;
drop table if exists creator_categories;
drop table if exists creator_profiles;
drop table if exists brand_profiles;
drop table if exists wallet_transactions;
drop table if exists withdrawals;
drop table if exists wallets;

-- One role for everyone: the same account sells and buys.
update users set role = 'USER' where role <> 'ADMIN';
-- The "advertise us for 500₸" task was creator-only and has no meaning here.
alter table users drop column if exists reward_task_paid;

create table user_profiles (
    id           bigint generated by default as identity primary key,
    user_id      bigint       not null unique references users (id) on delete cascade,
    display_name varchar(120) not null,
    phone        varchar(40)  not null,
    city         varchar(80)  not null,
    avatar_url   varchar(500),
    about        varchar(500),
    created_at   timestamptz  not null default now()
);

create table listings (
    id               bigint generated by default as identity primary key,
    seller_id        bigint        not null references users (id) on delete cascade,
    brand            varchar(20)   not null,
    model            varchar(120)  not null,
    storage_gb       integer       not null,
    ram_gb           integer,
    color            varchar(40),
    phone_condition  varchar(20)   not null,
    battery_health   integer,
    price            integer       not null,
    city             varchar(80)   not null,
    description      varchar(3000) not null,
    status           varchar(20)   not null,
    reject_reason    varchar(500),
    views            integer       not null default 0,
    created_at       timestamptz   not null default now(),
    updated_at       timestamptz   not null default now(),
    sold_at          timestamptz
);
create index idx_listings_status on listings (status);
create index idx_listings_seller on listings (seller_id);
create index idx_listings_brand on listings (brand);
create index idx_listings_city on listings (city);
create index idx_listings_price on listings (price);

create table listing_images (
    id         bigint generated by default as identity primary key,
    listing_id bigint       not null references listings (id) on delete cascade,
    url        varchar(500) not null,
    sort_order integer      not null default 0
);
create index idx_listing_images_listing on listing_images (listing_id);

-- A buyer's purchase request for one listing. One request per (listing, buyer).
create table deals (
    id         bigint generated by default as identity primary key,
    listing_id bigint        not null references listings (id) on delete cascade,
    buyer_id   bigint        not null references users (id) on delete cascade,
    status     varchar(20)   not null,
    message    varchar(1000),
    created_at timestamptz   not null default now(),
    updated_at timestamptz   not null default now(),
    unique (listing_id, buyer_id)
);
create index idx_deals_listing on deals (listing_id);
create index idx_deals_buyer on deals (buyer_id);
create index idx_deals_status on deals (status);

create table favorites (
    id         bigint generated by default as identity primary key,
    user_id    bigint      not null references users (id) on delete cascade,
    listing_id bigint      not null references listings (id) on delete cascade,
    created_at timestamptz not null default now(),
    unique (user_id, listing_id)
);
create index idx_favorites_user on favorites (user_id);
